name: Test build Scaffold

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
      working-directory: ./scaffold
    - name: Lint with pylint
      run: |
        make lint
      working-directory: ./scaffold
    - name: Test with pytest
      run: |
        make test
      working-directory: ./scaffold
    - name: Format code
      run: |
        make format
      working-directory: ./scaffold
